# play with dispatch vs push triggering and joining up the
# values
name: 00 Triggered from Manual Dispatch Sha

permissions:
  contents: read


on:
  workflow_dispatch:
    inputs:
      image_sha:
        description: "Input a string sha"
        required: true
        type: string

jobs:
  start-wf-manual:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: pre-call-info
        env:
          IN_SHA: ${{ inputs.image_sha }}
        run: |
          echo ":notice: trigging from tag, sha is is $IN_SHA"


  call-gotinput:
    # this needs a version or commit hash
    # uses: digikata/action-test/.github/workflows/10-gotinput.yaml@vABC

    # this variant doesn't
    uses: ./.github/workflows/10-gotinput.yaml
    with:
      image_sha: ${{ inputs.image_sha }}

