# play with dispatch vs push triggering and joining up the
# values
name: Triggered

permissions:
  contents: read


on:
  # trigger on platform tags
  push:
   tags:
     - 'v*'
  workflow_dispatch:
    inputs:
      image_sha:
        description: "Input a string sha"
        required: true
        type: string

jobs:
  trial-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set_image_sha_from_git_tag
        run: |
          echo "image_sha=${GIT_SHA} >> $GITHUB_OUTPUT

      - name: pre-call-info
        env:
          IN_SHA: ${{ inputs.image_sha }}
        run: |
          echo ":notice: image_tag is $IN_SHA"
          echo "image_sha=${GIT_SHA} >> $GITHUB_OUTPUT

  call-gotinput:
    # this needs a version or commit hash
    # uses: digikata/action-test/.github/workflows/10-gotinput.yaml@vABC

    # this variant doesn't
    uses: ./.github/workflows/10-gotinput.yaml
