# play with dispatch vs push triggering and joining up the
# values
name: 01 Triggered from Tag

permissions:
  contents: read


on:
  # trigger on platform tags
  push:
   tags:
     - 'b*'

jobs:
  tag1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: pre-call-info
        id: info
        run: |-
          echo ":notice: image_tag is $GITHUB_SHA"
          echo "image_sha=$GITHUB_SHA" >> $GITHUB_OUTPUT


      # this needs a version or commit hash
      # uses: digikata/action-test/.github/workflows/10-gotinput.yaml@vABC
      # this variant doesn't
      - name: callit
        uses: ./.github/workflows/10-gotinput.yaml
        with:
          image_sha: ${{ steps.info.outputs.image_sha }}


