# play with dispatch vs push triggering and joining up the
# values
name: GotAnInput

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      image_sha:
        description: "Input a string sha"
        required: true
        type: string

jobs:
  run-with-input:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: got an input
        env:
          IN_SHA: ${{ inputs.image_sha }}
        run: |-
          echo :notice: image_sha is $IN_SHA
          if [ -z $IN_SHA ]; then
            echo ":error:" Blank image_sha
            exit 1
          fi

