# play with dispatch vs push triggering and joining up the
# values
name: 11 jobenv

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  setmyenv:
    runs-on: ubuntu-latest

    steps:
      - name: set it
        run: |
          echo MYENV=foo >> $GITHUB_ENV

  what-is-my-env:
    runs-on: ubuntu-latest
    needs: [setmyenv]
    steps:
      - name: env
        run: |
          echo MYENV ${{ env.MYENV }}
      - name: env2
        env:
          MYENV2: ${{ env.MYENV }}
        run: |
          echo MYENV2 ${MYENV2}

