name: 20 Trigger or Tag

permissions:
  contents: read

on:
  # trigger on platform tags
  push:
   tags:
     - 'v*'
  workflow_dispatch:
    inputs:
      image_sha:
        description: "Input a string sha"
        required: true
        type: string

jobs:
  set_inputs:
    runs-on: ubuntu-latest
    outputs:
      image_sha: ${{ steps.from_dispatch.outputs.image_sha_com }}

    steps:
      - name: Setup Environment (manual dispatch)
        id: from_dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        shell: bash
        run: |
          echo "image_sha=${{ inputs.image_sha }}" >> ${GITHUB_ENV}
      - name: Setup Environment (Push)
        id: from_push
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          echo "image_sha=${GITHUB_SHA}" >> ${GITHUB_ENV}

  operate:
    needs: set_inputs
    runs-on: ubuntu-latest
    steps:
      - name: Operate step1
        shell: bash
        run: |
          echo IMAGE_SHA=${{ set_inputs.outputs.image_sha }}
