name: 20 Trigger or Tag

permissions:
  contents: read

on:
  # trigger on platform tags
  push:
   tags:
     - 'v*'
  workflow_dispatch:
    inputs:
      image_sha:
        description: "Input a string sha"
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image_sha_com: ${{ steps.info.outputs.image_sha_com }}

    steps:
      - name: Setup Environment (manual dispath)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        shell: bash
        run: |
          echo "IMAGE_SHA_COM=${{ github.event.inputs.image_tag}}" >> ${GITHUB_ENV}
      - name: Setup Environment (Push)
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          echo "IMAGE_SHA_COM=${{ github.event.sha}}" >> ${GITHUB_ENV}

  operate:
    runs-on: ubuntu-latest
    steps:
      - name: Operate step1
        shell: bash
        run: |
          echo IMAGE_SHA=${IMAGE_SHA_COM}

