name: 30 RD Send

on:
  workflow_dispatch:

jobs:
  fire_event:
    runs-on: ubuntu-latest
    steps:
      - name: repo dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: repo-ev
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
      - name: Done
        run: |
          echo Done

