
name: 31 Recv Repository Dispatch

on:
  repository_dispatch:
    types: [ repo-ev ]

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - name: Received
        run: |
          echo Received event
      - name: Setup
        run: |
          echo REF ${{ github.event.client_payload.ref }}
          echo SHA ${{ github.event.client_payload.sha }}
          echo "GITHUB_SHA=${{ github.event.client_payload.sha }}" >> $GITHUB_ENV
          echo "github_sha=${{ github.event.client_payload.sha }}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_SHA }}
      - name: Note
        run: |
          cat NOTE
  j2:
    needs: j1
    runs-on: ubuntu-latest
    env: 
      GITHUB_SHA: ${{needs.j1.outputs.github_sha }}
      PR_SHA: ${{needs.j1.outputs.github_sha }}
    steps:
      - name: Sha
        run: |
          echo env.SHA ${{ env.GITHUB_SHA }}
          echo GITHUB_SHA "$GITHUB_SHA"
          echo PR_SHA "$PR_SHA"
      - uses: actions/checkout@v4
        with:
          ref: ${PR_SHA}
      - name: Note
        run: |
          cat NOTE
    
    
