
name: Recv Repository Dispatch

on:
  repository_dispatch:
    types: [ repo-ev ]

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo Received event
      - run: |
        echo ${{ github.event.client_payload.sha }}
        echo "GITHUB_SHA=${{ github.event.client_payload.sha }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Note
        run: |
          cat NOTE

