
name: 31 Recv Repository Dispatch

on:
  repository_dispatch:
    types: [ repo-ev ]
  workflow_dispatch:
    inputs:
      sha:
        type: String
        required: true
jobs:
  j1:
    runs-on: ubuntu-latest
    outputs:
      github_sha: ${{ steps.final.outputs.github_sha }}
      github_ref: ${{ steps.final.outputs.github_ref }}
    steps:
      - name: Default Info
        run: |
          echo event_name ${{ github.event_name }}
          echo GITHUB_REF: "$GITHUB_REF"
          echo GITHUB_SHA: "$GITHUB_SHA"
          echo "github_ref=${{ env.GITHUB_REF }}" >> $GITHUB_OUTPUT
          echo "github_sha=${{ env.GITHUB_SHA }}" >> $GITHUB_OUTPUT
      - name: Setup for Repo Dispatch 
        if: github.event_name == 'repository_dispatch'
        run: |
          echo REF ${{ github.event.client_payload.ref }}
          echo SHA ${{ github.event.client_payload.sha }}
          echo "GITHUB_REF=${{ github.event.client_payload.ref }}" >> $GITHUB_ENV
          echo "GITHUB_SHA=${{ github.event.client_payload.sha }}" >> $GITHUB_ENV
      - name: Setup for Manual Run 
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo REF none
          echo SHA ${{ github.event.client_payload.sha }}
          echo "GITHUB_REF=none" >> $GITHUB_ENV
          echo "GITHUB_SHA=${{ github.event.inputs.sha }}" >> $GITHUB_ENV
      - name: Output
        id: final
        run: |
          GITHUB_SHA="${{ env.GITHUB_SHA }}"
          echo GITHUB_SHA: "$GITHUB_SHA"
          echo "github_ref=${{ env.GITHUB_REF }}" >> $GITHUB_OUTPUT
          echo "github_sha=${{ env.GITHUB_SHA }}" >> $GITHUB_OUTPUT
  j2:
    needs: j1
    runs-on: ubuntu-latest
    env: 
      GITHUB_SHA: ${{needs.j1.outputs.github_sha }}
      PR_SHA: ${{needs.j1.outputs.github_sha }}
    steps:
      - name: Sha
        run: |
          echo env.SHA ${{ env.GITHUB_SHA }}
          echo GITHUB_SHA "$GITHUB_SHA"
          echo PR_SHA "$PR_SHA"
      - uses: actions/checkout@v4
        with:
          ref:  ${{ env.PR_SHA }}
      - name: Note
        run: |
          cat NOTE
    
    
