
name: 31 Recv Repository Dispatch

on:
  repository_dispatch:
    types: [ repo-ev ]

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - name: Received
        run: |
          echo Received event
      - name: Sha
        run: |
          echo REF ${{ github.event.client_payload.ref }}
          echo SHA ${{ github.event.client_payload.sha }}
          echo "GITHUB_SHA=${{ github.event.client_payload.sha }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_SHA }}
      - name: Note
        run: |
          cat NOTE
  j2:
    runs-on: ubuntu-latest
    steps:
      - name: Sha
        run: |
          echo SHA ${{ env.GITHUB_SHA }}
    
